session_name: helpme-project

# https://github.com/tmux-python/tmuxp/tree/master/examples

# tmux cheatsheet https://gist.github.com/MohamedAlaa/2961058

before_script: |
  docker compose up --build -d

windows:
  - window_name: dev
    layout: tiled
    panes:
      - shell_command:
        - docker compose logs --follow db
      - shell_command:
        - docker compose logs --follow minio
      - shell_command:
        - docker compose logs --follow rabbitmq
      - shell_command:
        - docker compose logs --follow osrm-car osrm-foot osrm-bicycle
      - shell_command:
        - docker compose logs --follow nominatim
      - shell_command:
        - docker compose logs --follow tileserver-gl
      - shell_command:
        - docker compose logs --follow hasura
      - shell_command:
        - docker compose logs --follow hasura_console
      - shell_command:
        - docker compose logs --follow api
      - shell_command:
        - docker compose logs --follow files
      - shell_command:
        - docker compose logs --follow watchers
      - shell_command:
        - docker compose logs --follow tasks
      - shell_command:
        - yarn dev:web
      