session_name: helpme-project

# https://github.com/tmux-python/tmuxp/tree/master/examples

# tmux cheatsheet https://gist.github.com/MohamedAlaa/2961058

before_script: |
  up

windows:
  - window_name: dev
    layout: tiled
    panes:
      - shell_command:
        - docker compose logs --follow --tail=10 db minio rabbitmq redis-hot-geodata redis-q-dedup keydb-cold-geodata
      - shell_command:
        # - docker compose logs --follow tileserver-gl osrm-car osrm-foot osrm-bicycle nominatim
        - docker compose logs --follow --tail=10 tileserver-gl osrm-car osrm-foot nominatim
      - shell_command:
        - docker compose logs --follow --tail=10 hasura hasura_console
      - shell_command:
        - docker compose logs --follow --tail=10 api files
      - shell_command:
        - docker compose logs --follow --tail=10 watchers tasks
      - shell_command:
        - yarn dev:web
      