-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."archived_alert" add column "acknowledged_relative_count" integer
--  not null default '0';
