-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."alert" add column "acknowledged_relative" integer
--  not null default '0';
