-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."relative_invitation" add column "notification_sent" boolean
--  null;
