-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."relative_unregistered" add column "reconciliation_checked" boolean
--  not null default 'false';
